#driver=org.mariadb.jdbc.Driver
#url=jdbc:mysql://192.168.1.78:3306/project0
#url=jdbc:hsqldb:fsObject:../../tmp/db/project0
url=jdbc:hsqldb:hsql://localhost/project0
driver-class-name=org.hsqldb.jdbcDriver
username=root
password=0af3b424
