FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /workspace

# Copy maven wrapper and pom files
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY unipost-core/pom.xml unipost-core/
COPY unipost-resources/pom.xml unipost-resources/
COPY unipost-fw/pom.xml unipost-fw/
COPY unipost-db/pom.xml unipost-db/
COPY unipost-ms-fs/pom.xml unipost-ms-fs/
COPY unipost-ms-identity/pom.xml unipost-ms-identity/
COPY unipost-report-engine/pom.xml unipost-report-engine/
COPY unipost-ms-worker/pom.xml unipost-ms-worker/
COPY unipost-ms-aio/pom.xml unipost-ms-aio/

# Download dependencies
RUN ./mvnw dependency:go-offline -B

# Copy source code
COPY . .

# Build the jar
RUN ./mvnw -pl unipost-ms-aio -am clean package -DskipTests
RUN cp unipost-ms-aio/target/unipost-ms-aio-*.jar /workspace/app.jar

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app
COPY --from=builder /workspace/app.jar app.jar

# Create a CDS archive during the build phase by doing a training run
RUN java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-XX:SharedArchiveFile=application.jsa", "-jar", "app.jar"]
