// automatically generated by the FlatBuffers compiler, do not modify

package com.project0.fbs.fun4vn;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Fun4vn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Fun4vn getRootAsFun4vn(ByteBuffer _bb) { return getRootAsFun4vn(_bb, new Fun4vn()); }
  public static Fun4vn getRootAsFun4vn(ByteBuffer _bb, Fun4vn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean Fun4vnBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "F4VN"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Fun4vn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.project0.fbs.fun4vn.Article articles(int j) { return articles(new com.project0.fbs.fun4vn.Article(), j); }
  public com.project0.fbs.fun4vn.Article articles(com.project0.fbs.fun4vn.Article obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int articlesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public com.project0.fbs.fun4vn.Article articlesByKey(long key) { int o = __offset(4); return o != 0 ? com.project0.fbs.fun4vn.Article.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public com.project0.fbs.fun4vn.Article articlesByKey(com.project0.fbs.fun4vn.Article obj, long key) { int o = __offset(4); return o != 0 ? com.project0.fbs.fun4vn.Article.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public com.project0.fbs.fun4vn.Article.Vector articlesVector() { return articlesVector(new com.project0.fbs.fun4vn.Article.Vector()); }
  public com.project0.fbs.fun4vn.Article.Vector articlesVector(com.project0.fbs.fun4vn.Article.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public com.project0.fbs.fun4vn.Category categories(int j) { return categories(new com.project0.fbs.fun4vn.Category(), j); }
  public com.project0.fbs.fun4vn.Category categories(com.project0.fbs.fun4vn.Category obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int categoriesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public com.project0.fbs.fun4vn.Category categoriesByKey(byte key) { int o = __offset(6); return o != 0 ? com.project0.fbs.fun4vn.Category.__lookup_by_key(null, __vector(o), key, bb) : null; }
  public com.project0.fbs.fun4vn.Category categoriesByKey(com.project0.fbs.fun4vn.Category obj, byte key) { int o = __offset(6); return o != 0 ? com.project0.fbs.fun4vn.Category.__lookup_by_key(obj, __vector(o), key, bb) : null; }
  public com.project0.fbs.fun4vn.Category.Vector categoriesVector() { return categoriesVector(new com.project0.fbs.fun4vn.Category.Vector()); }
  public com.project0.fbs.fun4vn.Category.Vector categoriesVector(com.project0.fbs.fun4vn.Category.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createFun4vn(FlatBufferBuilder builder,
      int articlesOffset,
      int categoriesOffset) {
    builder.startTable(2);
    Fun4vn.addCategories(builder, categoriesOffset);
    Fun4vn.addArticles(builder, articlesOffset);
    return Fun4vn.endFun4vn(builder);
  }

  public static void startFun4vn(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addArticles(FlatBufferBuilder builder, int articlesOffset) { builder.addOffset(0, articlesOffset, 0); }
  public static int createArticlesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startArticlesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addCategories(FlatBufferBuilder builder, int categoriesOffset) { builder.addOffset(1, categoriesOffset, 0); }
  public static int createCategoriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startCategoriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFun4vn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishFun4vnBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "F4VN"); }
  public static void finishSizePrefixedFun4vnBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "F4VN"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Fun4vn get(int j) { return get(new Fun4vn(), j); }
    public Fun4vn get(Fun4vn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

