apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREE1TVRZeApOVFU0TXpWYUZ3MDBNREE1TVRZeE5UVTRNelZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFET3ZmU0V5NU8rdWd0MjN3ZmpJYUFzL290WXFCQ2pTMWVoQWl3N2R1bSszL003RXVYdgovajJQQnpIQk0wbUpXeGRadUJUMHZSYlhnS3JLQ1JNeGZ4alNoVExLUUdORzdVSXZyczJ0U29IOTltQjBjNXFUClllNWNwalMwU0ZUMjBjT1ppUmVqS2dmT2xHWjhkbUJwOWxkVnlBQXRhZFd3KzB6d3F2ekI0M3hwTHhmMGpEWm0KOVZ1QjhJYTltK25iSVRudnlNTG1YaXE4QjExd09IMTFzM3ZFeGlWeVRTVVlBVkFyKzgyeDVDQjJXT1BBbUNGNQpubERIZzRteTkwRUxhQ0hsMUpVcUNDTi9KOUxDbnlUNW9xSXFPckJkTVE4cno1dHJjWXlOY0Jzbnd4YlZWQUdzCmVSWFJuS3kwNW5pcHJrNGhJa0VIbHIvWnk1dWplbHIyYjBXckFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlR3YzgxV3dLcEhqejRTcGtQbgpTZkd4V2ZwMm9qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFaZTlUVk5zK3pkMzZFTmxZSWE3bEsya0hOaWE2Cng0dExtWThVekNmNE1jTmUzMDlqazFpUjZrdUs1eG5JalRVSXN0YkwrTGJ3ZC9LdDBlOEFxUmFhMU1rSHVuK0YKbFFNN1NQU0VJV1cxZkFVOFJJcUxMTzduQnY3bTdFclNPMjNkNEdnNlcyaS9LYkdTd1g0QjVuVEdhS0dXL1pFKwp0OUtJSitKdmwwMWZFTSt6KzVla3lPSWVSZHEwWjkrbWVicnhYTUQxRUQwTllTU3Uwa3dISkpmU3NlL3hKU21mCkhRdWZOTll4cC9MUkkwaUFaK0d1Y3lyZG55M2J3UlF5b08rRVZUbitOYk40N1J6QjRXcHIweS90SnkvOXYrWHYKQ0gyNzdKVEUxUDUyR2ZjbUhqZzhYR3k4UjY3a3I2bnQ1OHRhQ1kxZEc1cVZ1RjlEWGpyY3hjL0oxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f60ef652-ba3a-4a79-9396-89edad64c42a.k8s.ondigitalocean.com
  name: do-sgp1-k8s-1-18-8-do-0-sgp1-1600271716251
contexts:
- context:
    cluster: do-sgp1-k8s-1-18-8-do-0-sgp1-1600271716251
    user: do-sgp1-k8s-1-18-8-do-0-sgp1-1600271716251-admin
  name: do-sgp1-k8s-1-18-8-do-0-sgp1-1600271716251
current-context: do-sgp1-k8s-1-18-8-do-0-sgp1-1600271716251
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-1-18-8-do-0-sgp1-1600271716251-admin
  user:
    token: 5d7892ed8bda9cc98a8f6d172aea3b19e1711812c862d9e3eaf35a6f4a9cb79b
