application:
  security:
    maxSession: 1
    sessionExpiredUrl: /api/auth/expire
    permitAlls:
      - /login
      - /register
      - /resources/**
      - /jsMsgSource*
      - /**/*
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /graphql
      - /graphiql
      - /graphiql/**
    jwtTokenHeader: Authorization
    jwtTokenSecret: VEdiOCM5e1soNSFKZV1eVw==
    jwtTokenExpiration: 604800
storage:
  location: /upload-files
################### Spring boot Configuration ##########################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    enabled: false
ribbon:
  eager-load:
    enabled: true
server:
  port : 8081
  jetty:
    threads:
      min: 10
      max: 32
      acceptors: 2
      selectors: 4
spring:
  application:
    name: project0-ms-account
  http:
    servlet:
      max-file-size: 2000MB
      max-request-size: 2000MB
      enabled: false
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /resources/**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  profiles:
    active: swagger
  redis:
    host : localhost
    #host : 192.168.50.253
    port : 6379
  main:
    web-environment: true
  data:
    redis:
      repositories:
        enabled: false

  datasource:
#    url: jdbc:hsqldb:file:../tmp/db/project0
    url: jdbc:hsqldb:hsql://localhost/project0
    driverClassName: org.hsqldb.jdbcDriver
    #url: jdbc:mysql://localhost:3306/ancloud_cloud
    #driver-class-name: com.mysql.jdbc.Driver
    #username: project0
    #password: 0af3b424
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: true
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 96
      minimum-idle: 10
      connection-timeout: 60000
      initialization-fail-fast: false
  jpa:
    database: default
    show-sql: false
    hibernate:
        ddl-auto: none
        naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
        hibernate:
            dialect: org.hibernate.dialect.HSQLDialect
#            dialect: org.hibernate.dialect.MySQL5Dialect
        search:
            default:
              directory_provider: filesystem
              indexBase: ../tmp/indexes/
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls
security:
  filter:
    order: 5

mybatis:
  type-aliases-package: com.project0
  mapper-locations: classpath*:mappers/*.xml
  config-location: classpath:mybatis-config.xml


springdoc:
  show-spring-data-pageable: false
  show-spring-data-rest: false

