apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-prometheus
spec:
  rules:
  - http:
      paths:
        - path: /prometheus
          backend:
            serviceName: prometheus-operator-prometheus
            servicePort: 9090
