#driver=org.mariadb.jdbc.Driver
#url=jdbc:mysql://192.168.1.78:3306/unipost
#url=jdbc:hsqldb:fsObject:../../tmp/db/unipost
url=jdbc:hsqldb:hsql://localhost/unipost
driver-class-name=org.hsqldb.jdbcDriver
username=root
password=0af3b424
