// automatically generated by the FlatBuffers compiler, do not modify

package com.project0.fbs.fun4vn;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Article extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Article getRootAsArticle(ByteBuffer _bb) { return getRootAsArticle(_bb, new Article()); }
  public static Article getRootAsArticle(ByteBuffer _bb, Article obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Article __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public String uid() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer uidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String header() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer headerAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer headerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String summary() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer summaryAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer summaryInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public String content() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer contentAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer contentInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public String tags(int j) { int o = __offset(14); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int tagsLength() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public StringVector tagsVector() { return tagsVector(new StringVector()); }
  public StringVector tagsVector(StringVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public byte contentType() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createArticle(FlatBufferBuilder builder,
      long id,
      int uidOffset,
      int headerOffset,
      int summaryOffset,
      int contentOffset,
      int tagsOffset,
      byte content_type) {
    builder.startTable(7);
    Article.addTags(builder, tagsOffset);
    Article.addContent(builder, contentOffset);
    Article.addSummary(builder, summaryOffset);
    Article.addHeader(builder, headerOffset);
    Article.addUid(builder, uidOffset);
    Article.addId(builder, id);
    Article.addContentType(builder, content_type);
    return Article.endArticle(builder);
  }

  public static void startArticle(FlatBufferBuilder builder) { builder.startTable(7); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addInt(0, (int)id, (int)0L); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(1, uidOffset, 0); }
  public static void addHeader(FlatBufferBuilder builder, int headerOffset) { builder.addOffset(2, headerOffset, 0); }
  public static void addSummary(FlatBufferBuilder builder, int summaryOffset) { builder.addOffset(3, summaryOffset, 0); }
  public static void addContent(FlatBufferBuilder builder, int contentOffset) { builder.addOffset(4, contentOffset, 0); }
  public static void addTags(FlatBufferBuilder builder, int tagsOffset) { builder.addOffset(5, tagsOffset, 0); }
  public static int createTagsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTagsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addContentType(FlatBufferBuilder builder, byte contentType) { builder.addByte(6, contentType, 0); }
  public static int endArticle(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) {
    long val_1 = (long)_bb.getInt(__offset(4, o1, _bb)) & 0xFFFFFFFFL;
    long val_2 = (long)_bb.getInt(__offset(4, o2, _bb)) & 0xFFFFFFFFL;
    return val_1 > val_2 ? 1 : val_1 < val_2 ? -1 : 0;
  }

  public static Article __lookup_by_key(Article obj, int vectorLocation, long key, ByteBuffer bb) {
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      long val = (long)bb.getInt(__offset(4, bb.capacity() - tableOffset, bb)) & 0xFFFFFFFFL;
      int comp = val > key ? 1 : val < key ? -1 : 0;
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return (obj == null ? new Article() : obj).__assign(tableOffset, bb);
      }
    }
    return null;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Article get(int j) { return get(new Article(), j); }
    public Article get(Article obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
    public Article getByKey(long key) {  return __lookup_by_key(null, __vector(), key, bb); }
    public Article getByKey(Article obj, long key) {  return __lookup_by_key(obj, __vector(), key, bb); }
  }
}

