// automatically generated by the FlatBuffers compiler, do not modify

package com.project0.fbs.fun4vn;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Category extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Category getRootAsCategory(ByteBuffer _bb) { return getRootAsCategory(_bb, new Category()); }
  public static Category getRootAsCategory(ByteBuffer _bb, Category obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Category __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte id() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String uid() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer uidAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer uidInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String code() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer codeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer codeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String description() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long articleIds(int j) { int o = __offset(12); return o != 0 ? (long)bb.getInt(__vector(o) + j * 4) & 0xFFFFFFFFL : 0; }
  public int articleIdsLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public IntVector articleIdsVector() { return articleIdsVector(new IntVector()); }
  public IntVector articleIdsVector(IntVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer articleIdsAsByteBuffer() { return __vector_as_bytebuffer(12, 4); }
  public ByteBuffer articleIdsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 4); }

  public static int createCategory(FlatBufferBuilder builder,
      byte id,
      int uidOffset,
      int codeOffset,
      int descriptionOffset,
      int article_idsOffset) {
    builder.startTable(5);
    Category.addArticleIds(builder, article_idsOffset);
    Category.addDescription(builder, descriptionOffset);
    Category.addCode(builder, codeOffset);
    Category.addUid(builder, uidOffset);
    Category.addId(builder, id);
    return Category.endCategory(builder);
  }

  public static void startCategory(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addId(FlatBufferBuilder builder, byte id) { builder.addByte(0, id, 0); }
  public static void addUid(FlatBufferBuilder builder, int uidOffset) { builder.addOffset(1, uidOffset, 0); }
  public static void addCode(FlatBufferBuilder builder, int codeOffset) { builder.addOffset(2, codeOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(3, descriptionOffset, 0); }
  public static void addArticleIds(FlatBufferBuilder builder, int articleIdsOffset) { builder.addOffset(4, articleIdsOffset, 0); }
  public static int createArticleIdsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt(data[i]); return builder.endVector(); }
  public static void startArticleIdsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endCategory(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  @Override
  protected int keysCompare(Integer o1, Integer o2, ByteBuffer _bb) {
    byte val_1 = _bb.get(__offset(4, o1, _bb));
    byte val_2 = _bb.get(__offset(4, o2, _bb));
    return val_1 > val_2 ? 1 : val_1 < val_2 ? -1 : 0;
  }

  public static Category __lookup_by_key(Category obj, int vectorLocation, byte key, ByteBuffer bb) {
    int span = bb.getInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb);
      byte val = bb.get(__offset(4, bb.capacity() - tableOffset, bb));
      int comp = val > key ? 1 : val < key ? -1 : 0;
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return (obj == null ? new Category() : obj).__assign(tableOffset, bb);
      }
    }
    return null;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Category get(int j) { return get(new Category(), j); }
    public Category get(Category obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
    public Category getByKey(byte key) {  return __lookup_by_key(null, __vector(), key, bb); }
    public Category getByKey(Category obj, byte key) {  return __lookup_by_key(obj, __vector(), key, bb); }
  }
}

