// automatically generated by the FlatBuffers compiler, do not modify

package com.project0.fbs.fun4vn;

public final class ContentType {
  private ContentType() { }
  public static final byte TXT = 0;
  public static final byte HTML = 1;

  public static final String[] names = { "TXT", "HTML", };

  public static String name(int e) { return names[e]; }
}

