application:
  jms:
    enabled: true
    broker:
      url: "tcp://192.168.99.100:32768/"
      username: admin
      password: admin
  security:
    maxSession: 1
    sessionExpiredUrl: /api/auth/expire
    tokenUrl: api/auth/token
    tokenInvalidateUrl: api/auth/logout
    permitAlls:
      - /login
      - /register
      - /actuator/health
      - /resources/**
      - /jsMsgSource*
      - /api/auth/token
      - /api/scheduler/**
      - /fs/explorer/**
    jwtCookieName: X-AUTH-TOKEN
    jwtCookieDomain:
    jwtCookiePath: /
    jwtCookieSecure: false
    jwtTokenHeader: Authorization
    jwtTokenSecret: OTMxMURGMEJFMjA0MTBFOEUyMUIzQTU1MjFGMzkxRTFBODM5Mzc1MkZDNUNGQkM4ODUyNTU2RENERUI3RkVGREVGODVFMjZENDQ2MkE3MjcyMTk2MDlDNzE5NDg3MzgyNEE2RDZDQ0QwMTA3Qjg4REFDRUI5OUZEMUYwQ0MwMDI=
    jwtTokenExpiration: 360000000 # 60 * 60 * 1000 * 100 = 6000 mins
    jwtTokenExpirationWeb: 3600000 # 60 * 60 * 1000 = 60 mins
    jwtTokenExpirationMobile: 3600000 # 60 * 60 * 1000 = 60 mins
    jwtTokenExpirationDesktop: 3600000 # 60 * 60 * 1000 = 60 mins
    jwtRefreshTokenExpiration: 2592000000 # 30 * 24 * 60 * 60 * 1000 = 30 days

  storage:
    file-system:
      location: ../../tmp/upload-files
      cluster: e50d0471-aea2-40ba-af1b-32e5c6ae8e2b
    s3:
      defaultBucket: vpos-space
      url: http://192.168.1.104:9000
      region: sgp1
      key: minioadmin
      secret: minioadmin
  serviceEndpoints:
    identity: project0-ms-aio
    fs: project0-ms-aio
    cms: project0-ms-aio
  service:
    path:
      fs-upload: http://${application.serviceEndpoints.fs}/api/fs/upload/{uid}/{overwrite}
  redis:
    host: localhost
    port: 6379
##### Spring configuration properties #####
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false
        requestInterceptors:
          - com.project0.fw.client.interceptor.FeignContextInterceptor
logging:
  config: classpath:logback-local.xml

#Spring actuator configuration
management:
  health:
    mail:
      enabled: false
    jms:
      enabled: false
    redis:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}
      profiles: ${spring.profiles.active}
    enable:
      all: true
    export:
      jmx:
        enabled: true
      prometheus:
        enabled: true
    web:
      client:
        request:
          metric-name: http.client.requests

spring:
  redis:
    host: localhost
    #host : 192.168.50.253
    port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    bootstrap:
      enabled: false
    consul:
      enabled: false
      host: localhost
      port: 8500
      config:
        enabled: false
        fail-fast: true
      discovery:
        enabled: false
        register: false
  datasource:
#    url: jdbc:mariadb://localhost:3306/project0?max_statement_time=0
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: lamca
#    password: lamca
    url: jdbc:postgresql://localhost:5432/project0?charSet=UTF-8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
#    url: jdbc:hsqldb:file:../../tmp/db/project0
#    url: jdbc:hsqldb:hsql://localhost/project0
#    driver-class-name: org.hsqldb.jdbcDriver
#    username: root
#    password: 0af3b424
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idleTimeout: 10000
      maximumPoolSize: 96
      minimumIdle: 10
      connectionTimeout: 60000
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: jokkionle@gmail.com
    password: 0af3b424
    properties:
      mail:
        transport.protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
